import { Button } from '@chakra-ui/button'
import { Image } from '@chakra-ui/image'
import { Input } from '@chakra-ui/input'
import { Box, Flex, Spacer, Text } from '@chakra-ui/layout'
import Head from 'next/head'
import { useState } from 'react'
import TweetCard from '../components/tweetCard'
// import styles from '../styles/Home.module.css'

export default function Home() {
  
    const [loading, isLoading] = useState(false)
    const [username, setUsername] = useState('')
    const [message, setMessage] = useState(null)
    const fetchTweets = async()=>{
        try{

        }catch(err ){
            c
        }
    }


  return (
    <Flex direction="column" w="100vw" h='auto'>
      <Head>
        <title>Best Tweets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Flex direction='column' w="100%" h='auto'>
        {/* header */}
        <Flex  w='full' h='20' mb='20'>
             <Spacer />
                <Box p='4' bg='green.400'>
                    Night Mode
                </Box>
        </Flex>
        {/* end of header */}
        {/* main section */}
        <Flex direction='column' justify='center' align='center' textAlign='center' w='full' h='full'>
            <Text fontSize='2xl' fontWeight='bold' m='2'>My Best Tweets 🚀</Text>
            <Text fontSize='xl' m='2' color='gray.400'>Find the best tweets posted by any user.</Text>
            <Flex direction='column'  m='4' justifyContent='center' alignItems='center'
            width={[
                "100vw", // base
                "80vw", // 480px upwards
                "80vw", // 768px upwards
                "50vw", // 992px upwards
                ]}
            >
            
                <Flex direction='row' m='2' h='12' 
                width={[
                "100vw", // base
                "80vw", // 480px upwards
                "80vw", // 768px upwards
                "40vw", // 992px upwards
                ]}
                >
               
                <Input placeholder='Enter name of handle' m='1' h='full' w='80%'/>
                <Button colorScheme='green' m='1' h='full' w='20%'>Submit</Button>
                </Flex>
                {/* tweets container */}
                <Flex direction='column' justifyContent='center' m='5' w='full'  alignItems='center'>
                   {/* tweet card */}
                       <TweetCard/>
                       <TweetCard/>
                       <TweetCard/>
                       <TweetCard/>
                   {/* end of tweet card */}
                </Flex>
                {/* end of tweets container */}
                
            </Flex>
        </Flex>
        {/* end of main section */}
    </Flex>
    </Flex>
  )
}
